server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: library_user
    password: library_pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    com.example.library: DEBUG
    org.hibernate.SQL: DEBUG
